#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Demander l'élévation des privilèges dès le début
sudo -v

# Bonne pratique, pour définir le répertoire du script
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR

# --------------------
# Variables globales
# --------------------
# Contrôle du visuel
SHOW_HELP=0
SHOW_BANNER=0
SHOW_VERSION=0
SHOW_EE=0
# Contrôle du comportement
ACTION=""
declare -a MODULE_WHITELIST=()

# --------------------
# Importer les librairies
# --------------------
source "$SCRIPT_DIR/core/libs.sh"

# --------------------
# Parser les arguments
# --------------------

# Si nous n'arrivons pas à parser les arguments, nous affichons l'aide et ne lançons par la potentielle action valide
if ! parse_args "$@"; then
    SHOW_HELP=1
fi

# Passer en readonly les variables globales de contrôle, maintenant que l'hydratation est faite (ou non)
readonly SHOW_HELP
readonly SHOW_BANNER
readonly SHOW_VERSION
readonly SHOW_EE
readonly ACTION
readonly MODULE_WHITELIST
readonly LOG_LEVEL

# --------------------
# Chargement du registre
# --------------------
reg_bootstrap

# --------------------
# Executer l'action
# --------------------
menu_show

if [[ -n "$ACTION" && $SHOW_HELP -eq 0 ]]; then
    # Execution de l'action demandée
    action_execute
fi

exit 0